defaults: &defaults
  postgresql:
    host: <%= ENV['POSTGRESQL_HOST'] || 'localhost' %>
    username: <%= ENV['POSTGRESQL_USERNAME'] %>
    password: <%= ENV['POSTGRESQL_PASSWORD'] %>

development: &development
  <<: *defaults

test:
  <<: *development

production:
  <<: *defaults